version: '3'
services:
  olta_back:
    container_name: olta_back
    ports:
      - "3000:3000"
    build:
      context: ./back
    environment:
      DATABASE_URL: $DATABASE_URL
      DB_USERNAME: $DB_USERNAME 
      DB_PASSWORD: $DB_PASSWORD 
      DB_NAME: $DB_NAME 
      DB_HOST: $DB_HOST
  nginx-container:
    container_name: 'nginx-container'
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./olta.conf:/etc/nginx/conf.d/default.conf
      - ./olta-site:/usr/share/nginx/html
      - ./dh-param/dhparam-2048.pem:/etc/ssl/certs/dhparam-2048.pem
      - /docker-volumes/etc/letsencrypt/live/olta.fr/fullchain.pem:/etc/letsencrypt/live/olta.fr/fullchain.pem
      - /docker-volumes/etc/letsencrypt/live/olta.fr/privkey.pem:/etc/letsencrypt/live/olta.fr/privkey.pem